version: '3.7'

volumes:
  pgdata:
  
services:
  app:
    image: resourcesss_look:latest
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    ports:
      - $APP_PORT:8080
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: sh -c "/app/init.sh"
  migrate:
    image: resourcesss_look:latest
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: resourcesss_look:latest
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
